In [1]:
import nest_asyncio
nest_asyncio.apply() 
import twint
import pandas as pd

c = twint.Config()
c.Since = "2022-01-01"
c.Until = "2022-07-01"
c.Lang = "id"
c.Limit = 300
c.Search = 'pln_123'
c.Hide_output = True
c.Debug = True
c.Pandas = True

In [2]:
%%time
try:
    print("Start Crawling")
    
    def twint_to_dataframe(colums):
        return twint.output.panda.Tweets_df[colums]
    
    #start crawling
    twint.run.Search(c)
    
    data = twint_to_dataframe(['date','username','tweet'])
    
except Exception as e:
    print(e)
    
print("Finished")

Start Crawling
Finished
Wall time: 8.66 s

In [3]:
data

,date,username,tweet
0,2022-07-01 06:59:09,rahinahu461,"@pln_123 Mohon maaf, sy tidak mencantumkan per..."
1,2022-07-01 06:55:51,nandosbs_,@pln_123 Tindaklanjuti hanya dengan tulisan ka...
2,2022-07-01 06:54:10,BennyKeef,"@pln_123 Min listrik di rmh ada masalah, saya ..."
3,2022-07-01 06:36:42,aleendy_,@pln_123 halo min boleh cek DM?
4,2022-07-01 06:33:44,pln_123,"@timelinism Hai Kak, Mhn maaf ya perihal kenda..."
...,...,...,...
310,2022-06-30 13:45:05,azeezy84,"@pln_123 listrik area Salam, Magelang mati dar..."
311,2022-06-30 13:37:41,pln_123,"@oscarokay82 Maaf atas kendalanya ya Kak, pe..."
312,2022-06-30 13:34:22,pln_123,"@pn_frog Maaf atas kendalanya ya Kak, periha..."
313,2022-06-30 13:30:38,pln_123,"@megaaku Hai Kak Mega, mohon maaf ya perihal k..."
314,2022-06-30 13:28:53,fransiskanovin4,@pln_123 kak daerah malang singosari mati lamp...

In [4]:
data.to_csv('craw_pln123_new_06-07-2022-1.csv', index=False)